name: Docker Image CI

on:
  # push:
  #  branches:
  #    - master
  workflow_dispatch:  # 触发手动事件


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  #  - name: Build the Docker image
  #    run: docker build . --file Dockerfile --tag :$(date +%s)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: denny0810/chandleraiapi:latest
